let
    // Conexão com a API de localidades do IBGE
    Fonte = Json.Document(Web.Contents("https://servicodados.ibge.gov.br/api/v1/localidades/municipios")),
    // Conversão da conexão com a API para a tabela primária de registros
    Tabela = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    // Expansão dos registros da tabela primária, para obtenção dos dados dos municípios, com código e nome, mais colunas adicionais de registros das Microrregiões e Regiões Imediatas
    Municipios = Table.ExpandRecordColumn(Tabela, "Column1", {"id", "nome", "microrregiao", "regiao-imediata"}, {"id", "nome", "microrregiao", "regiao-imediata"}),
    // Expansão da coluna de registros das Microrregiões para obtenção dos dados respectivos, mais coluna adicional com registros das Mesorregiões.
    Microrregiao = Table.ExpandRecordColumn(Municipios, "microrregiao", {"id", "nome", "mesorregiao"}, {"microrregiao.id", "microrregiao.nome", "microrregiao.mesorregiao"}),
    // Expansão da coluna de registros das Mesorregiões, para obtenção dos dados respectivos, mais colua de registros da UF.
    Mesorregiao = Table.ExpandRecordColumn(Microrregiao, "microrregiao.mesorregiao", {"id", "nome", "UF"}, {"microrregiao.mesorregiao.id", "microrregiao.mesorregiao.nome", "microrregiao.mesorregiao.UF"}),
    // Expansão da coluna de Regiões Imediatas, para obtenção dos dados respectivos, mais coluna de registros com dados das Regiões Intermediárias.
    Imediata = Table.ExpandRecordColumn(Mesorregiao, "regiao-imediata", {"id", "nome", "regiao-intermediaria"}, {"regiao-imediata.id", "regiao-imediata.nome", "regiao-imediata.regiao-intermediaria"}),
    // Expansão das Regiões Intermediárias para obtenção dos dados respectivos, mais obtenção da coluna de registros com dados da UF
    Intermediaria = Table.ExpandRecordColumn(Imediata, "regiao-imediata.regiao-intermediaria", {"id", "nome", "UF"}, {"regiao-imediata.regiao-intermediaria.id", "regiao-imediata.regiao-intermediaria.nome", "regiao-imediata.regiao-intermediaria.UF"}),
    // Expansão da coluna UF para obtenção dos dados relativos aos estados, mais coluna de registros das regiões do Brasil.
    UF = Table.ExpandRecordColumn(Intermediaria, "regiao-imediata.regiao-intermediaria.UF", {"id", "sigla", "nome", "regiao"}, {"regiao-imediata.regiao-intermediaria.UF.id", "regiao-imediata.regiao-intermediaria.UF.sigla", "regiao-imediata.regiao-intermediaria.UF.nome", "regiao-imediata.regiao-intermediaria.UF.regiao"}),
    // Expansão da coluna de registros das Regiões do país.
    Regiao = Table.ExpandRecordColumn(UF, "regiao-imediata.regiao-intermediaria.UF.regiao", {"id", "sigla", "nome"}, {"regiao-imediata.regiao-intermediaria.UF.regiao.id", "regiao-imediata.regiao-intermediaria.UF.regiao.sigla", "regiao-imediata.regiao-intermediaria.UF.regiao.nome"}),
    // Definição do layout final da tabela, com eliminação de colunas repetidas e desnecessárias.
    Layout = Table.SelectColumns(Regiao,{"id", "nome", "microrregiao.id", "microrregiao.nome", "microrregiao.mesorregiao.id", "microrregiao.mesorregiao.nome", "regiao-imediata.id", "regiao-imediata.nome", "regiao-imediata.regiao-intermediaria.id", "regiao-imediata.regiao-intermediaria.nome", "regiao-imediata.regiao-intermediaria.UF.id", "regiao-imediata.regiao-intermediaria.UF.sigla", "regiao-imediata.regiao-intermediaria.UF.nome", "regiao-imediata.regiao-intermediaria.UF.regiao.id", "regiao-imediata.regiao-intermediaria.UF.regiao.sigla", "regiao-imediata.regiao-intermediaria.UF.regiao.nome"}),
    // Tipificação dos dados em TEXTO.
    TipoAlterado = Table.TransformColumnTypes(Layout,{{"id", type text}, {"nome", type text}, {"microrregiao.id", type text}, {"microrregiao.nome", type text}, {"microrregiao.mesorregiao.id", type text}, {"microrregiao.mesorregiao.nome", type text}, {"regiao-imediata.id", type text}, {"regiao-imediata.nome", type text}, {"regiao-imediata.regiao-intermediaria.id", type text}, {"regiao-imediata.regiao-intermediaria.nome", type text}, {"regiao-imediata.regiao-intermediaria.UF.id", type text}, {"regiao-imediata.regiao-intermediaria.UF.sigla", type text}, {"regiao-imediata.regiao-intermediaria.UF.nome", type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.id", type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.sigla", type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.nome", type text}}),
    // Eliminação de espaços desnecessários das cadeias de caracteres.
    TextoAparado = Table.TransformColumns(TipoAlterado,{{"id", Text.Trim, type text}, {"nome", Text.Trim, type text}, {"microrregiao.id", Text.Trim, type text}, {"microrregiao.nome", Text.Trim, type text}, {"microrregiao.mesorregiao.id", Text.Trim, type text}, {"microrregiao.mesorregiao.nome", Text.Trim, type text}, {"regiao-imediata.id", Text.Trim, type text}, {"regiao-imediata.nome", Text.Trim, type text}, {"regiao-imediata.regiao-intermediaria.id", Text.Trim, type text}, {"regiao-imediata.regiao-intermediaria.nome", Text.Trim, type text}, {"regiao-imediata.regiao-intermediaria.UF.id", Text.Trim, type text}, {"regiao-imediata.regiao-intermediaria.UF.sigla", Text.Trim, type text}, {"regiao-imediata.regiao-intermediaria.UF.nome", Text.Trim, type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.id", Text.Trim, type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.sigla", Text.Trim, type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.nome", Text.Trim, type text}}),
    // Eliminação de quebras de linhas, tabulações e caracteres não imprimíveis nas cadeias de textos.
    TextoLimpo = Table.TransformColumns(TextoAparado,{{"id", Text.Clean, type text}, {"nome", Text.Clean, type text}, {"microrregiao.id", Text.Clean, type text}, {"microrregiao.nome", Text.Clean, type text}, {"microrregiao.mesorregiao.id", Text.Clean, type text}, {"microrregiao.mesorregiao.nome", Text.Clean, type text}, {"regiao-imediata.id", Text.Clean, type text}, {"regiao-imediata.nome", Text.Clean, type text}, {"regiao-imediata.regiao-intermediaria.id", Text.Clean, type text}, {"regiao-imediata.regiao-intermediaria.nome", Text.Clean, type text}, {"regiao-imediata.regiao-intermediaria.UF.id", Text.Clean, type text}, {"regiao-imediata.regiao-intermediaria.UF.sigla", Text.Clean, type text}, {"regiao-imediata.regiao-intermediaria.UF.nome", Text.Clean, type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.id", Text.Clean, type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.sigla", Text.Clean, type text}, {"regiao-imediata.regiao-intermediaria.UF.regiao.nome", Text.Clean, type text}}),
    // Aplicação de camada semântica para o usuário final.
    ColunasRenomeadas = Table.RenameColumns(TextoLimpo,{{"id", "Cód. Mun. IBGE"}, {"nome", "Município"}, {"microrregiao.id", "Cód. Microrregião"}, {"microrregiao.nome", "Microrregião"}, {"microrregiao.mesorregiao.id", "Cód. Mesorregião"}, {"microrregiao.mesorregiao.nome", "Mesorregião"}, {"regiao-imediata.id", "Cód. Região Imediata"}, {"regiao-imediata.nome", "Região Imediata"}, {"regiao-imediata.regiao-intermediaria.id", "Cód. Região Intermediária"}, {"regiao-imediata.regiao-intermediaria.nome", "Região Intermediária"}, {"regiao-imediata.regiao-intermediaria.UF.id", "Cód. UF"}, {"regiao-imediata.regiao-intermediaria.UF.sigla", "UF"}, {"regiao-imediata.regiao-intermediaria.UF.nome", "Estado"}, {"regiao-imediata.regiao-intermediaria.UF.regiao.id", "Cód. Região"}, {"regiao-imediata.regiao-intermediaria.UF.regiao.sigla", "Sigla Região"}, {"regiao-imediata.regiao-intermediaria.UF.regiao.nome", "Região"}})
in
    ColunasRenomeadas
